export const styles = {
  root: {
    height: "100vh",
  },
  headingStyle: {
    color: "#000",
    textRendering: "optimizeLegibility",
    fontVariantCaps: "all-small-caps",
    // fontFamily: "Roboto",
    fontSize: "36px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "167%",
  },
  title: {
    color: "var(--Black, #000)",
    // fontFamily: "Roboto",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "167%",
  },
  uploadBox: {
    borderRadius: "4px",
    border: "1px dashed var(--Main-Blue, #0A6EB7)",
    background: "#F8F8FF",
    height: "202px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    cursor: "pointer",
  },
  upload_image: {
    color: "#0F0F0F",
    textAlign: "center",
    // fontFamily: "Roboto",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "24px",
    margin: "10px 0",
  },
  s_format: {
    color: "#676767",
    textAlign: "center",
    // fontFamily: "Roboto",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "18px",
  },
  s_format2: {
    color: "#676767",
    // fontFamily: "Roboto",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "18px",
  },
  btn: {
    display: "inline-flex",
    height: "49px",
    padding: "16px 31px 17px 30px",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    borderRadius: "3px",
    border: "1px solid var(--Main-Blue, #0A6EB7)",
    // marginTop: "40px",
  },
  location_box: {
    height: "368px",
    flexShrink: 0,
    borderRadius: "14px",
    background:
      "url(/location.png), lightgray 0px -269.003px / 100% 224.458% no-repeat",
  },
  chip_box: {
    display: "inline-flex",
    height: "49px",
    padding: "0px 42px",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    borderRadius: "30px",
    cursor: "pointer",
  },
  radio_text: {
    color: "var(--gray, #7E7E7E)",
    fontFeatureSettings: "'clig' off, 'liga' off",
    // fontFamily: "Roboto",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "24px",
  },
  c_a: {
    height: "87px",
    flexShrink: 0,
    borderRadius: "4px",
    border: "1px solid #DCDCE4",
    background: "var(--White, #FFF)",
    padding: "15px",
  },
  c_a_t: {
    color: "var(--Gray-1, #8E8EA9)",
    fontFeatureSettings: "'clig' off, 'liga' off",
    // fontFamily: "Roboto",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "24px",
  },
  t: {
    color: "var(--Light-mode-Neutral800, #32324D)",
    fontFeatureSettings: "'clig' off, 'liga' off",
    // fontFamily: "Roboto",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "16px",
  },
  btn_submit: {
    width: "140px",
    height: "46px",
    flexShrink: 0,
    borderRadius: "4px",
    background: "var(--Main-Blue, #0A6EB7)",
    color: "#fff",
    marginBottom: "30px",
    ":hover": {
      background: "#0A6EB7",
    },
  },
};
