export const styles = {
  heading: {
    color: "#000",
    // fontFamily: "Inter",
    fontSize: "22px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "136%",
  },
  valueStyle: {
    color: "var(--Main-Blue, #0A6EB7)",
    // fontFamily: "Inter",
    fontSize: "36px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "normal",
    textTransform: "uppercase",
  },
  text: {
    color: "#656565",
    // fontFamily: "Inter",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "136%",
  },
  text2: {
    color: "#000",
    textAlign: "right",
    // fontFamily: "Inter",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "136%",
  },
  c_req: {
    color: "#000",
    leadingTrim: "both",
    textEdge: "cap",
    // fontFamily: "Roboto",
    fontSize: "25px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "167%",
  },
  p_detail: {
    color: "var(--Main-Blue, #0A6EB7)",
    // fontFamily: "Roboto",
    fontSize: "30px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
    marginBottom: "50px",
    "@media (max-width: 500px)": {
      fontSize: "25px",
      marginBottom: "30px",
    },
  },
  desc: {
    color: "var(--Black, var(--Black, #000))",
    // fontFamily: '"Source Sans Pro"',
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  det: {
    color: "#7E7E7E",
    // fontFamily: "Roboto",
    fontSize: "21px",
    fontStyle: "normal",
    fontWeight: 300,
    lineHeight: "150%",
    marginTop: "20px",
    marginBottom: "50px",
  },
  amn: {
    color: "#343434",
    // fontFamily: "Roboto",
    fontSize: "17px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "150%",
  },
  g_btn: {
    display: "flex",
    // width: "615px",
    padding: "12px 0px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "5px",
    background: "#109D59",
    color: "#fff",
    "&:hover": {
      background: "#109D59",
    },
  },
  r_btn: {
    display: "flex",
    // width: "615px",
    padding: "12px 0px",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "5px",
    background: "#EC4D4A",
    color: "#fff",
    "&:hover": {
      background: "#EC4D4A",
    },
  },
  sara: {
    color: "var(--Black, #000)",
    // fontFamily: "Inter",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "normal",
    textTransform: "capitalize",
  },
  loc_text: {
    color: "var(--Black, #000)",
    textAlign: "right",
    // fontFamily: "Inter",
    fontSize: "18px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "136%",
  },
};
